sudo: false
language: node_js
node_js:
  - "8"
  - "7"
  - "6"

services:
  - docker

before_install:
  - docker pull vicanso/varnish:4.1.3
  - docker run -d --net="host" -e PORT=8081 -v $TRAVIS_BUILD_DIR/examples/varnish4/default.vcl:/etc/varnish/default.vcl vicanso/varnish:4.1.3

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
