name: $HOSTNAME
stale: 2
varnish: "5"
directors:
  -
    name: timtam
    service: timtam
    type: fallback
    ping: /my-ping
    backends:
      -
        ip: 127.0.0.1
        port: 3000
      -
        ip: 127.0.0.1
        port: 3010
  -
    name: dcharts
    prefix: /dcharts
    host:
      - dcharts.com
      - www.dcharts.com
    type: hash
    hashKey: req.http.cookie
    backends:
      -
        ip: 127.0.0.1
        port: 3020
        weight: 5
      -
        ip: 127.0.0.1
        port: 3030
        weight: 3
  -
    name: vicanso
    host: vicanso.com
    type: random
    backends:
      -
        ip: 127.0.0.1
        port: 3040
        weight: 10
      -
        ip: 127.0.0.1
        port: 3050
        weight: 5
  -
    name: aslant
    backends:
      -
        ip: 127.0.0.1
        port: 8000
