#!/usr/bin/env node

const program = require('commander');
const path = require('path');

const pkg = require('../package');
const generator = require('..');

program
  .version(pkg.version)
  .option('-c, --config <n>', 'The config file, eg: ~/config.json')
  .option('-t, --target <n>', 'The file for vcl, eg: ~/default.vcl')
  .parse(process.argv);


if (!program.config) {
  throw new Error('the config option can not be null');
}
generator.getVclFromFile(path.join(process.cwd(), program.config))
  .then((vcl) => {
    if (!program.target) {
      console.info(vcl);
      return Promise.resolve();
    }
    return generator.writeVclToFile(program.target, vcl);
  })
  .catch(console.error);
