name: varnish-test
stale: 2
varnish: 4
directors:
  -
    name: timtam
    prefix: /timtam
    type: fallback
    backends:
      -
        ip: 127.0.0.1
        port: 3000
      -
        ip: 127.0.0.1
        port: 3010
  -
    name: dcharts
    prefix: /dcharts
    host: dcharts.com
    type: hash
    hashKey: req.http.cookie
    backends:
      -
        ip: 127.0.0.1
        port: 3000
        weight: 5
      -
        ip: 127.0.0.1
        port: 3030
        weight: 3
